version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.robolectric:robolectric
    versions:
    - "4.5"
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 4.1.2
  - dependency-name: org.mockito:mockito-core
    versions:
    - 3.7.7
  - dependency-name: com.google.android.gms:play-services-location
    versions:
    - 17.1.0
  - dependency-name: com.google.android.gms:play-services-wearable
    versions:
    - 17.0.0
