language: android

before_install: chmod +x gradlew

android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.1
    - android-27
    - extra-android-m2repository

script: ./gradlew test
